name = "sona-nimi"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2026-04-09"

[vars]
NODE_VERSION = "20"
PNPM_VERSION = "9"
PUBLIC_BASE_URL = "https://api.linku.la/"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "0f8d630d30dc445691bcbfb9c5d37d92"
